### ISSUE TITLE
Questions about data augmentation.

### ISSUE THREAD

**Issue by BaoWentz** [linxuewu/Sparse4D#11]
Thanks for your good job!

There is a small question for me, why put GridMask augmentation here rather than train_pipeline? This seems not that elegant, thanks.
https://github.com/linxuewu/Sparse4D/blob/c48ecd2b020d7770faaa865f577eed28406b75e9/projects/mmdet3d_plugin/models/sparse4d.py#L57

**Comment by linxuewu** [comment]
You are right, grid_mask is more suitable to be placed in the pipeline. This problem is mainly because our code-base (DETR3D) is written like this. And I have tried to put it into the pipeline before, the training speed seems to have dropped a little bit, so I didn’t change it. But I didn’t further investigate why the training slowed down (maybe it fluctuated).
