### ISSUE TITLE
why don't learn local yaw?

### ISSUE THREAD

**Issue by BaoWentz** [linxuewu/Sparse4D#29]
I wonder why we don't learn local yaw but yaw, will local yaw be better?

**Comment by linxuewu** [comment]
What coordinate system and axis does 'local yaw' refer to in the context of rotation angle?

**Comment by BaoWentz** [comment]
I mean in camera coordinate system、 y axis and [alpha](https://blog.csdn.net/weixin_44675423/article/details/127736859?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522169580112216800182116137%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=169580112216800182116137&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v1~rank_v31_ecpm-1-127736859-null-null.142^v94^chatsearchT3_1&utm_term=%E5%8D%95%E7%9B%AE3d%20alpha&spm=1018.2226.3001.4187) angle.

**Comment by linxuewu** [comment]
Because we are a multi-view model with multiple camera coordinate systems, yaw is not suitable to be defined within a camera coordinate system, especially when dealing with objects across different perspectives. However, if it is used for single-view perception, then it should be reverted to yaw in the camera coordinate system.
