### ISSUE TITLE
About mAOE in r50

### ISSUE THREAD

**Issue by InchSoup** [linxuewu/Sparse4D#49]
Thank you for your outstanding work and valuable open-source contributions.
I have observed that the mAOE metric of Sparse4D is slightly inferior in r50 configurations compared to recent release methods (StreamPETR, SparseBEV and DynamicBEV),  but it holds a great advantage on other configurations (r101, v2-99).
Do you have an explanation for this phenomenon? Anticipating your reply.

**Comment by linxuewu** [comment]
The phenomenon is challenging to explain. 
1. For R50, the mAOE metric is not very stable, fluctuating between 0.44 and 0.50 for different experiments.
2. I believe that in situations where model capacity is limited, Sparse4D tends to prioritize optimizing distance error and classification accuracy rather than orientation error. However, in cases where the model capacity is larger and other error optimizations are already well-performed, Sparse4D then focuses on improving orientation accuracy. This is reminiscent of a multi-task optimization problem, where a comprehensive analysis of various metrics is necessary to reflect the model's performance.
3. It could also be a result of different training parameters; for models like R101, we make slight adjustments to lr/batch size parameters.

**Comment by InchSoup** [comment]
it has been very rewarding, thank you for your sharing.
